#!/bin/sh

# Runs a command for each URL.
#
# Arguments: [URL ...]

# FIXME refactor, cleanup
# FIXME document (including dependencies and setup)
#   sudo apt install libnotify-bin
# FIXME test (including shellcheck)
# FIXME error handling
# FIXME proper extensibility, example ideas:
#   - ext_cmd/on_enclosure_url.d/* (runs chmod +x files)
#   - run a specific command that must be in PATH
#   - run a command specified in an env var
#   - resolve symlinks and runs a config command
# TODO idea, accept `*.url` files
#   https://learn.microsoft.com/en-us/windows/win32/lwef/internet-shortcuts
#   https://nsis.sourceforge.io/Creating_internet_shortcuts

set -o errexit -o nounset

locate_youwee_in_wsl() {
    # Other alternatives that were explored:
    #
    # (A) Fastest, but too much parsing and hardcoding, making this brittle.
    #
    #    reg.exe query 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall' /s /f Youwee \
    #    | tr -d '\r' \
    #    | grep InstallLocation \
    #    | grep -oP '[^\s]*\\.+$' \
    #    | xargs -d '\n' wslpath
    #
    # (B) Slower, and still has some hardcoding.
    #
    #    powershell.exe -NonInteractive '(
    #      Get-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*
    #      | Where DisplayName -eq Youwee
    #    ).InstallLocation'
    #
    # (C) Faster, but fails if the shortcut is missing from the Start Menu.
    #
    #    powershell.exe -NonInteractive '(
    #        New-Object -ComObject Shell.Application
    #    ).NameSpace(
    #        "shell:AppsFolder"
    #    ).ParseName(
    #        "com.vanloctech.youwee"
    #    ).ExtendedProperty(
    #        "System.Link.TargetParsingPath"
    #    )'
    #
    # (D) Even faster, and ditto.
    #
    #    cscript.exe /Nologo /E:JScript TEMPFILE.js
    #
    #    [TEMPFILE.js]
    #    WScript.Echo(WScript.CreateObject('Shell.Application')
    #      .NameSpace('shell:AppsFolder')
    #      .ParseName('com.vanloctech.youwee')
    #      .ExtendedProperty('System.Link.TargetParsingPath'));

    # FIXME slow to run PowerShell, and slow to use `Get-Package`
    powershell.exe -NonInteractive '(Get-Package -Name Youwee).Source' \
        | tr -d '\r' \
        | xargs -d '\n' wslpath
}

run_youwee_via_wsl() {
    "$(locate_youwee_in_wsl)/youwee.exe" "$@"
}

is_in_wsl() {
    command -v wslpath >/dev/null
}

run_youwee() {
    if is_in_wsl; then
        run_youwee_via_wsl "$@"
    else
        youwee "$@"
    fi
}

# https://youwee.app
# https://youwee.app/docs/cli/
#
# Arguments: <URL> <quality>
download_via_youwee_cli() {
    # FIXME let yt-dlp choose format, eg. bestvideo[height<=?720]+bestaudio/best
    # FIXME option for other video formats (eg. mp4 doesn't embed metadata)
    # FIXME embed subtitles
    # FIXME embed metadata
    # TODO powershell.exe -Command 'Start-Process "shell:AppsFolder\com.vanloctech.youwee"'
    run_youwee --skip-live "--url=$1" "--quality=$2"
}

# https://github.com/mhogomchungu/media-downloader
#
# Arguments: <URL>
download_via_media_downloader() {
    flatpak run io.github.mhogomchungu.media-downloader \
        --auto-download --url "$1"
}

# FIXME ensure apps are always spawn in the background?
# FIXME call other alternatives if the default fails?
# TODO option for rolling downloads? eg. only the last `n` NRK news episodes
for url; do
    notify-send 'Enclosure URL' "$url"
    download_via_youwee_cli "$url" 720
#     download_via_media_downloader "$url"
#    . yt_dlp.sh && yt_defaults "$url"
done
