#!/bin/sh

# Runs a command for each URL.
# Calls `download_url_with_youwee` by default.
#
# Arguments: [URL ...]

# FIXME document (including dependencies and setup)
# FIXME test (including shellcheck)
# FIXME error handling
# FIXME proper extensibility, example ideas:
#   - ext_cmd/on_enclosure_url.d/* (runs chmod +x files)
#   - run a specific command that must be in PATH
#   - run a command specified in an env var
#   - resolve symlinks and runs a config command
# TODO idea, accept `*.url` files
#      https://learn.microsoft.com/en-us/windows/win32/lwef/internet-shortcuts
#      https://nsis.sourceforge.io/Creating_internet_shortcuts

set -o errexit -o nounset

# https://youwee.app
# https://youwee.app/docs/cli/
#
# Arguments: <URL> <quality>
download_via_youwee_cli() {
    # FIXME let yt-dlp choose format, eg. bestvideo[height<=?720]+bestaudio/best
    # FIXME option for other video formats (eg. mp4 doesn't embed metadata)
    # FIXME embed subtitles
    # FIXME embed metadata
    # TODO powershell.exe -Command 'Start-Process "shell:AppsFolder\com.vanloctech.youwee"'
    youwee --skip-live "--url=$1" "--quality=$2"
}

# https://github.com/mhogomchungu/media-downloader
#
# Arguments: <URL>
download_via_media_downloader() {
    flatpak run io.github.mhogomchungu.media-downloader \
        --auto-download --url "$1"
}

# FIXME ensure apps are always spawn in the background?
# FIXME call other alternatives if the default fails?
# TODO option for rolling downloads? eg. only the last `n` NRK news episodes
for url; do
    notify-send 'Enclosure URL' "$url"
    download_via_youwee_cli "$url" 720
#     download_via_media_downloader "$url"
#    . yt_dlp.sh && yt_defaults "$url"
done
