#!/bin/sh

# Runs a command for each URL.
#
# Arguments: [URL ...]

# TODO refactor
# TODO error handling
# TODO test (+ shellcheck)
# TODO document (+ dependencies + setup)

# TODO embed video subtitles
# TODO embed video metadata
# TODO skip YouTube shorts (vertical videos)
# TODO skip video if mtime > 1 year (eg. Last Week Tonight uploads old episodes)
# TODO make it possible to starts watching a video before completing download?

# TODO proper extensibility, example ideas:
#   - ext_cmd/on_enclosure_url.d/* (runs chmod +x files)
#   - run a specific command that must be in PATH
#   - run a command specified in an env var
#   - resolve symlinks and runs a config command

# TODO have an alternative to yt-dlp ready to go, when needed?
#   - https://jdownloader.org
#   - https://github.com/soimort/you-get
#   - https://github.com/TeamNewPipe/NewPipeExtractor
#   - https://github.com/Tyrrrz/YoutubeExplode
#   - https://github.com/LuanRT/YouTube.js
#   - https://github.com/imputnet/cobalt

# TODO idea, accept `*.url` files
#   - https://learn.microsoft.com/en-us/windows/win32/lwef/internet-shortcuts
#   - https://nsis.sourceforge.io/Creating_internet_shortcuts

set -o errexit -o nounset

# TODO re-add fallback to `youwee://` protocol?
# TODO re-add fallback to `shell:AppsFolder`?
locate_youwee_in_wsl() {
    # Check Package Management first, and only then resort to a registry query.
    # https://learn.microsoft.com/powershell/module/packagemanagement/get-package
    #
    # If Youwee is initially installed via an MSI installer and later updated,
    # then it will be relocated/re-installed to the user's `%APPDATA%`,
    # which `Get-Package` won't be able to locate.
    # TODO put fastest first? check HKLM too?
    { {
        powershell.exe -NonInteractive '(Get-Package -Name Youwee).Source' \
        | tr -d '\r' \
        | grep .
    } \
    || {
        reg.exe query 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Youwee' \
        | grep InstallLocation \
        | tr -d '\r' \
        | grep -oP '[^\s"]*\\[^"]+'
    } } \
    | xargs -d '\n' wslpath
}

run_youwee_via_wsl() {
    # TODO failing to run `ffmpeg` under Windows when Dropbox is running?
    "$(locate_youwee_in_wsl)/youwee.exe" "$@"
}

in_wsl() {
    command -v wslpath >/dev/null
}

run_youwee() {
    if in_wsl; then
        run_youwee_via_wsl "$@"
    else
        youwee "$@"
    fi
}

# https://youwee.app
# https://youwee.app/docs/cli/
#
# Arguments: <URL> <quality>
# TODO how to sort download queue from recent to old?
# TODO app is sluggish as AppImage only? vs via .deb install
# TODO disable previews altogether in the YouTube section
# TODO follow dark/light mode from OS? CLI option to change mode
# TODO show timestamp when download was added/finished in the queue
# TODO how to change number of parallel downloads, during downloading
download_via_youwee_cli() {
    # TODO let yt-dlp choose format, eg. bestvideo[height<=?720]+bestaudio/best
    # TODO option for other video formats (eg. mp4 doesn't embed metadata?)
    run_youwee --skip-live "--url=$1" "--quality=$2"
}

# https://github.com/mhogomchungu/media-downloader
#
# Arguments: <URL>
download_via_media_downloader() {
    flatpak run io.github.mhogomchungu.media-downloader \
        --auto-download --url "$1"
}

# TODO option for rolling downloads? eg. only the last `n` NRK news episodes
for url; do
    # TODO not currently working from within WSL
    # TODO notify only in case of errors to reduce distractions?
    if ! in_wsl; then
        notify-send 'Enclosure URL' "$url"
    fi

    # TODO ensure apps are always spawn in the background?
    download_via_youwee_cli "$url" 720

    # TODO call other alternatives if the default fails?
    #   download_via_media_downloader "$url"
    #   . yt_dlp.sh && yt_defaults "$url"
done
