[liferea]
# Last checked: https://github.com/lwindolf/liferea/tree/v1.16.7

# TODO use distrobox ephemeral?
# TODO create new base package w/ pre-installed dependencies? for startup time
# TODO how to handle initial password requirement?
# TODO document
#   $ distrobox assemble create
#   $ env -i distrobox enter liferea -- liferea

image=ubuntu:26.04
start_now=true
unshare_all=true
init=true

# TODO remove hardcoded home path?
home=/tmp/liferea-box

additional_packages=liferea

# Required by the `download-manager` plugin:
#   https://github.com/lwindolf/liferea/issues/1584
additional_packages=python3-requests

# Required by the `gnome-keyring` plugin.
# TODO file GitHub issue?
additional_packages=gir1.2-secret-1

# TODO setup `venv` for `ext_cmd`
additional_packages=python3-venv

# TODO finish plugin setup
#    python3 -m venv ~/venv
#    . ~/venv/bin/activate
#    pip install 'pip>=26'
#
#    ln -s /home/.../ark/ ~/
#    cd ~/ark/scripts/adapters/liferea/
#    pip install --requirements-from-script path_to.py
#
#    # TODO remove once `ext_cmd` is fixed to handle this missing dependency
#    apt install gir1.2-peas-2
#
#    # setup plugin symlink
#    (deactivate && liferea)
