[base]

# Features:
#
# - Enables `apt` caching of downloaded packages, to speed up container runs.
#
# - Disables locale generation, to speed up container runs.
#
# - Enables NVidia support and forces software-based video rendering, to avoid
#   errors from polluting logs.
#
# - Provides a `asuser` shell function, to run commands as a non-root user in
#   `init_hooks`.
#
# - Provides a `dq` shell function, to print literal double-quotes for use in
#   `pre_init_hooks`.
#
# - Provides a `divert` shell function, to selectively disable a specified
#   binary using `dpkg-divert` (as a symlink to `true`) for use in
#   `pre_init_hooks`.
#
# - Provides a `setenv` shell function, to add a variable in the
#   `/etc/environment` file in `init_hooks`.

# TODO create new base package w/ pre-installed dependencies? to speed up
# TODO skip `apt-get update`?
# TODO how to handle initial password requirement?
image=ubuntu:26.04

# Prints a single literal double quote.
# TODO file GitHub issue on Distrobox?
# - double quote behavior != `init_hook`
# - find out exact file format for manifest files
# - `init-hooks` flag overrides previous flags vs appending like manifest file
pre_init_hooks="dq() { printf Ig== | base64 -d; }"

# Cache packages.
# See: https://hub.docker.com/r/docker/dockerfile#example-cache-apt-packages
# See: https://salsa.debian.org/apt-team/apt/-/blob/1.2/debian/NEWS
volume=~/.cache/distrobox-apt-ubuntu-26-04:/var/cache/apt/archives
pre_init_hooks="rm -v -f /etc/apt/apt.conf.d/docker-clean"
pre_init_hooks="{ printf \"APT::Keep-Downloaded-Packages \"; dq; printf true; dq; echo \";\"; } | tee /etc/apt/apt.conf.d/01_keep-pkgs"

# Divert a binary to `true`, effectively disabling it.
# TODO is this idempotent?
pre_init_hooks="divert() { dpkg-divert --local --divert \"\$1.real\" --rename --add \"\$1\" && ln -s -v -f /bin/true \"\$1\"; }"

# Disable locale generation.
# TODO could this break anything?
pre_init_hooks="divert /usr/sbin/locale-gen"
pre_init_hooks="divert /usr/sbin/update-locale"

init_hooks="setenv() { grep -q -F "$1" /etc/environment || echo "$1" | tee -a /etc/environment; }"

# Avoid video rendering errors.
nvidia=true
# TODO will `LIBGL_ALWAYS_SOFTWARE=true` make Liferea too slow?
init_hooks="setenv LIBGL_ALWAYS_SOFTWARE=true"
# TODO should this be set only where needed? for Liferea v2?
init_hooks="setenv GSK_RENDERER=gl"

# Runs a command as non-root.
# TODO remove non-root user hack
# - https://github.com/89luca89/distrobox/issues/2170
# - replace `stat` with a Posix compliant impl?
init_hooks="asuser() { runuser -u "$(stat -c %U ~)" -- "$@"; }"

[liferea-base]

# Installs required dependencies for the `download-manager` and `gnome-keyring`
# plugins.

include=base
unshare_all=true
init=true

# Required by the `download-manager` plugin:
#   https://github.com/lwindolf/liferea/issues/1584
additional_packages=python3-requests

# Required by the `gnome-keyring` plugin.
# TODO file Liferea bug?
#    (net.sourceforge.liferea:12891): libsecret-CRITICAL **: 17:36:12.213: secret_service_load_collections_sync: assertion 'paths != NULL' failed
#    Traceback (most recent call last):
#        File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 49, in do_query
#        coll = self.get_collection()
#        File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 39, in get_collection
#        colls = service.get_collections()
#        ^^^^^^^^^^^^^^^^^^^^^^^
#    AttributeError: 'NoneType' object has no attribute 'get_collections'
# - else -
#    ** (net.sourceforge.liferea:16778): WARNING **: 17:42:56.176: Error importing plugin 'gnome-keyring':
#    Traceback (most recent call last):
#        File "/usr/lib/python3.14/importlib/__init__.py", line 88, in import_module
#        return _bootstrap._gcd_import(name[level:], package, level)
#        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#        File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
#        File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
#        File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
#        File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
#        File "<frozen importlib._bootstrap_external>", line 759, in exec_module
#        File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
#        File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 22, in <module>
#        gi.require_version('Secret', '1')
#        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
#        File "/usr/lib/python3/dist-packages/gi/__init__.py", line 150, in require_version
#        raise ValueError(f"Namespace {namespace} not available")
#    ValueError: Namespace Secret not available
additional_packages="gir1.2-secret-1 gnome-keyring"

[liferea-v1]

# Last checked: https://github.com/lwindolf/liferea/tree/v1.16.7

# TODO use distrobox ephemeral?
#   $ env -i distrobox ephemeral --clone liferea --home "`mktemp -d`" --unshare-all --init -- liferea
# TODO document
#   $ distrobox assemble create
#   $ docker logs -f liferea
#   # TODO make entering the container automatically launch the app, by default?
#   $ env -i distrobox enter liferea -- liferea

include=liferea-base
start_now=true

# TODO remove hardcoded home path?
home=/tmp/distrobox-home-liferea-v1

additional_packages=liferea

# Setup Python environment for installing the plugin.
# TODO cache Python packages? see also `.cache/pip/`
additional_packages=python3-venv
init_hooks="asuser sh -c "python3 -m venv ~/venv && . ~/venv/bin/activate && pip install pip\>=26""

# TODO remove hardcoded home path?
# TODO simplify
volume=.:/tmp/distrobox-home-liferea-v1/plugin:ro
init_hooks="asuser sh -c ". ~/venv/bin/activate && pip install --requirements-from-script ~/plugin/path_to.py && ~/plugin/path_to.py plugins | xargs mkdir -v -p && ~/plugin/path_to.py plugins | xargs ln -s -v -f ~/plugin/ext_cmd/""

[liferea-v2]

include=liferea-base
start_now=true

# TODO remove hardcoded home path?
home=/tmp/distrobox-home-liferea-v2

# See: https://github.com/lwindolf/liferea/blob/main/.github/workflows/cb.yml
additional_packages="libxml2-dev libxslt1-dev libsqlite3-dev libwebkitgtk-6.0-dev libjson-glib-dev libgirepository-2.0-dev libpeas-2-dev gsettings-desktop-schemas-dev python3 libtool intltool valgrind libfribidi-dev gla11y appstream desktop-file-utils meson ninja-build gobject-introspection libadwaita-1-dev libdbus-1-dev"

# TODO missing from dependencies?
#    ** (net.sourceforge.liferea:16755): WARNING **: 00:02:14.520: Error initializing Python Plugin Loader: PyGObject initialization failed
#    ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))
#    ** (net.sourceforge.liferea:16755): WARNING **: 00:02:14.549: Please check the installation of all the Python related packages required by libpeas and try again
#    (net.sourceforge.liferea:16755): libpeas-WARNING **: 00:02:14.549: Loader 'python' is not a valid PeasPluginLoader instance
additional_packages="python3-gi"

# Release v2.0 has a breaking bug, so use the commit that fixes it.
# https://github.com/lwindolf/liferea/discussions/1585
#   init_hooks="curl -L https://github.com/lwindolf/liferea/releases/download/v2.0/liferea-2.0.tar.xz | asuser tar -x -v -J -f - -C ~/"
#   init_hooks="asuser mv -v ~/liferea-2.0/ ~/liferea/"
init_hooks="asuser curl -L -o ~/liferea.zip https://github.com/lwindolf/liferea/archive/145f52b30aa6568a6c7b1b0b38705f4628ce8a80.zip"
init_hooks="asuser unzip -d ~/ ~/liferea.zip"
init_hooks="asuser mv -v ~/liferea-*/ ~/liferea/"

init_hooks="asuser meson setup ~/build/ ~/liferea/"
init_hooks="asuser meson compile -C ~/build/"
init_hooks="asuser meson test -C ~/build/"
init_hooks="meson install -C ~/build/"
