[liferea]
# Last checked: https://github.com/lwindolf/liferea/tree/v1.16.7

# TODO create new base package w/ pre-installed dependencies? to speed up
# TODO disable locales? too slow
# TODO skip `apt-get update`?
# TODO how to handle initial password requirement?
# TODO use distrobox ephemeral?
#   $ env -i distrobox ephemeral --clone liferea --home "`mktemp -d`" --unshare-all --init -- liferea
# TODO document
#   $ distrobox assemble create
#   $ docker logs -f liferea
#   $ env -i distrobox enter liferea -- liferea

image=ubuntu:26.04
start_now=true
unshare_all=true
init=true

# Cache packages to speed up container creation on future runs.
# - https://hub.docker.com/r/docker/dockerfile#example-cache-apt-packages
# - https://salsa.debian.org/apt-team/apt/-/blob/1.2/debian/NEWS
volume=~/.cache/distrobox-apt-ubuntu-26-04:/var/cache/apt/archives
pre_init_hooks="rm /etc/apt/apt.conf.d/docker-clean && echo APT::Keep-Downloaded-Packages \\\"true\\\"\; | tee /etc/apt/apt.conf.d/01_keep-pkgs"

##
## LIFEREA
##

# TODO remove hardcoded home path?
home=/tmp/distrobox-home-liferea

additional_packages=liferea

# Required by the `download-manager` plugin:
#   https://github.com/lwindolf/liferea/issues/1584
additional_packages=python3-requests

# Required by the `gnome-keyring` plugin.
additional_packages=gir1.2-secret-1

##
## PLUGIN
##

# TODO remove non-root user hack
#   https://github.com/89luca89/distrobox/issues/2170
init_hooks='asuser() { runuser -u "$(stat -c %U ~)" -- "$@"; }'

# Setup Python environment for installing the plugin.
# TODO cache Python packages?
additional_packages=python3-venv
init_hooks='asuser sh -c "python3 -m venv ~/venv && . ~/venv/bin/activate && pip install \"pip>=26\""'

# TODO remove hardcoded home path?
volume=.:/tmp/distrobox-home-liferea/plugin:ro
init_hooks='asuser sh -c ". ~/venv/bin/activate && pip install --requirements-from-script ~/plugin/path_to.py"'

# TODO finish plugin setup
